spring.application.name=ims

# Database config
spring.datasource.url=jdbc:mysql://localhost:3306/codeb_ims?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a8d11c4d9a3493e843c98d6c750b3e5ea167cdeb611f7c220a2e5d14dfb0e21a

server.port=8080
